
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: argocd-defi-gitops
  description: Contains the ArgoCD manifests for argocd-defi
  annotations:
    argocd/app-name: argocd-defi-gitops
    backstage.io/kubernetes-id: argocd-defi-gitops
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: BlackMamba97s/argocd-defi-gitops
spec:
  type: gitops
  system: argocd
  lifecycle: production
  owner: BlackMamba97
  dependsOn:
    - component:default/backstagedocs
